<section class="content">
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-red">
      <div class="inner">
        <h3><?php Contador('trabajador'); ?></h3>
        <p>Registro de Empleados</p>
      </div>
      <div class="icon">
        <i class="fa fa-users"></i>
      </div>
      <a href="empleado.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-aqua">
      <div class="inner">
        <h3>-</h3>
        <p>Mantenimiento de Empleados</p>
      </div>
      <div class="icon">
        <i class="fa fa-gears"></i>
      </div>
      <a href="editempleado.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-green">
      <div class="inner">
        <h3><?php contadortbsinusu(); ?></h3>
        <p>Crear Usuario</p>
      </div>
      <div class="icon">
        <i class="ion ion-person-add"></i>
      </div>
      <a href="crearusuario.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-orange">
      <div class="inner">
        <h3><?php Contador('trabajador'); ?></h3>
        <p>Buscar Usuarios</p>
      </div>
      <div class="icon">
        <i class="fa fa-search"></i>
      </div>
      <a href="buscarusuario.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-blue">
      <div class="inner">
        <h3><?php contadorPer(); ?></h3>
        <p>Registro de Personas</p>
      </div>
      <div class="icon">
        <i class="fa fa-male"></i>
      </div>
      <a href="persona.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-red">
      <div class="inner">
        <h3><?php Contador('institucion'); ?></h3>
        <p>Registro de Instituciones</p>
      </div>
      <div class="icon">
        <i class="fa fa-institution"></i>
      </div>
      <a href="institucion.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-green">
      <div class="inner">
        <h3>-</h3>
        <p>Registro de Area y Cargos</p>
      </div>
      <div class="icon">
        <i class="fa fa-list-alt"></i>
      </div>
      <a href="areacargo.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-yellow">
      <div class="inner">
        <h3>-</h3>
        <p>Registro de Años, Proveido, Prioridad</p>
      </div>
      <div class="icon">
        <i class="fa fa-list-alt"></i>
      </div>
      <a href="tabla.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-aqua">
      <div class="inner">
        <h3>-</h3>
        <p>Directorio</p>
      </div>
      <div class="icon">
        <i class="fa fa-calendar-o"></i>
      </div>
      <a href="directorio.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
</section>
<section class="content"></section>
