<section class="content">
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-blue">
      <div class="inner">
        <h3>-</h3>
        <p>Ingresar Documentos</p>
      </div>
      <div class="icon">
        <i class="fa fa-file"></i>
      </div>
      <a href="ingresodoc.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-green">
      <div class="inner">
        <h3>-</h3>
        <p>Emitir Documentos</p>
      </div>
      <div class="icon">
        <i class="fa fa-file-text"></i>
      </div>
      <a href="emitirdoc.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-red">
      <div class="inner">
        <h3><?php contadorRec($dato); ?></h3>
        <p>Recepcion de Documentos</p>
      </div>
      <div class="icon">
        <i class="fa fa-download"></i>
      </div>
      <a href="recibirdoc.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-aqua">
      <div class="inner">
        <h3>_</h3>
        <p>Distribucion de Documentos</p>
      </div>
      <div class="icon">
        <i class="fa fa-upload"></i>
      </div>
      <a href="distribuciondoc.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>

  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-orange">
      <div class="inner">
        <h3><?php contadorArc($dato); ?></h3>
        <p>Archivo de Documentos</p>
      </div>
      <div class="icon">
        <i class="fa fa-archive"></i>
      </div>
      <a href="archivardoc.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-green">
      <div class="inner">
        <h3>_</h3>
        <p>Seguimiento de Documentos</p>
      </div>
      <div class="icon">
        <i class="fa fa-hand-grab-o"></i>
      </div>
      <a href="seguimientodoc.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-red">
      <div class="inner">
        <h3>_</h3>
        <p>Reporte de documentos historico</p>
      </div>
      <div class="icon">
        <i class="fa fa-folder"></i>
      </div>
      <a href="reporterec.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-aqua">
      <div class="inner">
        <h3><?php contadorPer(); ?></h3>
        <p>Documentos ingresados</p>
      </div>
      <div class="icon">
        <i class="ion ion-person-add"></i>
      </div>
      <a href="reporteing.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
    <!-- small box -->
    <div class="small-box bg-yellow">
      <div class="inner">
        <h3><?php contador('institucion'); ?></h3>
        <p>Documentos emitidos</p>
      </div>
      <div class="icon">
        <i class="fa fa-institution"></i>
      </div>
      <a href="reporteemit.php" class="small-box-footer">Mas informacion <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div>
</section>
<section class="content"></section>
